name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v2

    # Étape 2 : Installer les dépendances PHP
      - name: Install PHP dependencies
        run: composer install
        
         # Étape 3 : Installer les dépendances Angular
      - name: Install Angular dependencies
        run: |
         cd frontend
         npm install
